name = "RayCaster"
uuid = "17f63090-eba8-4cc7-872a-3f6808909c39"
authors = ["Siddharth Bhatia <sidb60200@gmail.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
